# Generated by Django 5.1.7 on 2025-04-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_customuser_email_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_otp_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=10),
        ),
    ]
