# Generated by Django 5.1.7 on 2025-04-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_customuser_preferred_otp_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
